### ISSUE TITLE
Error with proposal script against pre-release 0.30.0 core node software 

### ISSUE THREAD

**Issue by edd** [vegaprotocol/sample-api-scripts#49]
```
Logging into wallet: ******
Logged in to wallet successfully
Selected pubkey for signing
Found an asset with symbol tDAI
{'ID': '6d9d35f657589e40ddfb448b7ad4a7463b66efb307527fedd2aa7df1bbd5ea61', 'name': 'Dai (dev)', 'symbol': 'tDAI', 'totalSupply': '4577810003200000', 'decimals': '5', 'source': {'erc20': {'contractAddress': '0xBEaF29DCE23B39FAfa7BA59a1b3Feb8687f96782'}}}
Found governance asset account
{'id': '', 'owner': '66d7bfd5ea74609cd397946ca62eabee4fee89b75f452a8207ff4d25ad3a6a11', 'balance': '1', 'asset': 'f11862be7fc37c47372439f982a8f09912c4f995434120ff43ff51d9c34ef71a', 'marketID': '', 'type': 'ACCOUNT_TYPE_GENERAL'}
Blockchain time: 1611060037681064477 (1611060037 seconds past epoch)
Traceback (most recent call last):
  File "propose-markets/propose-vote-enact-market.py", line 231, in <module>
    helpers.check_response(response)
  File "/home/edd/src/vega/sample-api-scripts/helpers.py", line 8, in check_response
    assert (
AssertionError: https://.../governance/prepare/proposal returned HTTP 400 {
  "code": 3,
  "message": "InvalidArgument error",
  "details": [
    {
      "@type": "type.googleapis.com/vega.ErrorDetail",
      "code": 10015,
      "message": "malformed request",
      "inner": "invalid field Proposal.NewMarket.Changes.Instrument.Future.SettlementAsset: value '' must not be an empty string"
    }
  ]
}
```
I haven't gone to check, but I am guessing there is an upcoming breaking API change.

**Comment by edd** [comment]
It is due to: github.com/vegaprotocol/vega/pull/2821/

**Comment by edd** [comment]
After an embarrassing thread in the other repo, one shape change to take note of is that this property has been removed:

https://github.com/vegaprotocol/sample-api-scripts/blob/abcb30fb159bc30ea839b0b2276bc9eeaeb7684b/propose-markets/propose-vote-enact-market.py#L215

And is now calculated by:

https://github.com/vegaprotocol/sample-api-scripts/blob/abcb30fb159bc30ea839b0b2276bc9eeaeb7684b/propose-markets/propose-vote-enact-market.py#L181-L184

And this value here, of 10s, will be rejected.

So updating that and the asset name field will be sufficient.

**Comment by cdm** [comment]
Thanks @edd - Yes agreed, the market proposal scripts will need to be updated for 0.30.*
I'll reference this ticket in the related branch PR

**Comment by cdm** [comment]
Find in PR #51
